(function(g){var window=this;var a3=function(a,b,c,d){var e=b.sb();g.K(a.element,"ytp-suggestion-set",!!e.videoId);var f=b.getPlaylistId();d=b.oc(c,d?d:"mqdefault.jpg");var k=b instanceof g.nC?g.UO(b.lengthSeconds):null,l=!!f;f=l&&"RD"==(new g.kE(f.substr(0,2),f.substr(2))).type;var m=b instanceof g.nC?b.ra:null;c={title:b.title,author:b.author,author_and_views:e.shortViewCount?b.author+" \u2022 "+e.shortViewCount:b.author,aria_label:b.Bi||g.Q("YTP_WATCH_VIDEO_OR_PLAYLIST",{TITLE:b.title},b.title),duration:k,url:b.Ui(c),is_live:m,
is_list:l,is_mix:f,background:d?"background-image: url("+d+")":""};b instanceof g.mE&&(c.playlist_length=b.getLength());a.update(c)},b3=function(a,b){g.rv.call(this,{D:"div",
W:["html5-endscreen","ytp-player-content",b||"base-endscreen"]});this.l=a;this.created=!1},c3=function(a){g.R.call(this,{D:"div",
H:"ytp-upnext",O:{"aria-label":"{{aria_label}}"},K:[{D:"div",H:"ytp-cued-thumbnail-overlay-image",O:{style:"{{background}}"}},{D:"span",H:"ytp-upnext-top",K:[{D:"span",H:"ytp-upnext-header",V:"\ub2e4\uc74c \ub3d9\uc601\uc0c1"},{D:"span",H:"ytp-upnext-title",V:"{{title}}"},{D:"span",H:"ytp-upnext-author",V:"{{author}}"}]},{D:"a",H:"ytp-upnext-autoplay-icon",O:{role:"button",href:"{{url}}","aria-label":"\ub2e4\uc74c \ub3d9\uc601\uc0c1 \uc7ac\uc0dd"},K:[{D:"svg",O:{height:"100%",version:"1.1",viewBox:"0 0 72 72",
width:"100%"},K:[{D:"circle",H:"ytp-svg-autoplay-circle",O:{cx:"36",cy:"36",fill:"#fff","fill-opacity":"0.3",r:"31.5"}},{D:"circle",H:"ytp-svg-autoplay-ring",O:{cx:"-36",cy:"36","fill-opacity":"0",r:"33.5",stroke:"#FFFFFF","stroke-dasharray":"211","stroke-dashoffset":"-211","stroke-width":"4",transform:"rotate(-90)"}},{D:"path",H:"ytp-svg-fill",O:{d:"M 24,48 41,36 24,24 V 48 z M 44,24 v 24 h 4 V 24 h -4 z"}}]}]},{D:"span",H:"ytp-upnext-bottom",K:[{D:"span",H:"ytp-upnext-cancel"},{D:"span",H:"ytp-upnext-paused",
V:"\uc790\ub3d9\uc7ac\uc0dd \uc77c\uc2dc\uc911\uc9c0\ub428"}]}]});this.A=null;var b=this.g["ytp-upnext-cancel"];this.A=new g.R({D:"button",W:["ytp-upnext-cancel-button","ytp-button"],O:{tabindex:"0","aria-label":"\uc790\ub3d9\uc7ac\uc0dd \ucde8\uc18c"},V:"\ucde8\uc18c"});g.I(this,this.A);this.A.da("click",this.aH,this);this.A.aa(b);this.l=a;this.J=this.g["ytp-svg-autoplay-ring"];this.F=this.C=this.o=this.B=null;this.G=new g.L(this.vk,5E3,this);g.I(this,this.G);this.I=0;this.M(this.g["ytp-upnext-autoplay-icon"],
"click",this.UI);this.lw();this.M(a,"autonavvisibility",this.lw);this.M(a,"mdxnowautoplaying",this.hI);this.M(a,"mdxautoplaycanceled",this.iI);this.M(a,"mdxautoplayupnext",this.Oy);3==this.l.Ea()&&(a=(a=g.WJ(g.RJ(this.l)))?a.VA():null)&&this.Oy(a)},d3=function(a,b){a.B=b;
a3(a,b,g.V(a.l),"hqdefault.jpg")},e3=function(a,b){if(!a.o){g.Ut("a11y-announce","\ub2e4\uc74c \ub3d9\uc601\uc0c1 "+a.B.title);
a.I=g.P();a.o=new g.L((0,g.A)(a.mn,a,b),25);a.mn(b);var c=b||g.T(g.V(a.l).experiments,"autoplay_time")||1E4;a.l.ma("onAutonavCoundownStarted",c)}g.gq(a.element,"ytp-upnext-autoplay-paused")},g3=function(a){f3(a);
a.I=g.P();a.mn();g.J(a.element,"ytp-upnext-autoplay-paused")},f3=function(a){a.o&&(a.o.dispose(),a.o=null)},h3=function(a,b){b=void 0===b?!1:b;
var c=g.V(a.l);if(g.S(c.experiments,"autonav_notifications")&&b&&window.Notification&&window.document.hasFocus){var d=window.Notification.permission;"default"==d?window.Notification.requestPermission():"granted"!=d||window.document.hasFocus()||(d=a.B.sb(),a.vk(),a.C=new window.Notification("\ub2e4\uc74c \ub3d9\uc601\uc0c1",{body:d.title,icon:d.oc(c)}),a.F=a.M(a.C,"click",a.KI),a.G.start())}f3(a);a.l.Qh(!1,b)},i3=function(a){b3.call(this,a,"subscribecard-endscreen");
var b=a.getVideoData();this.o=new g.R({D:"div",H:"ytp-subscribe-card",K:[{D:"img",H:"ytp-author-image",O:{src:b.profilePicture}},{D:"div",H:"ytp-subscribe-card-right",K:[{D:"div",H:"ytp-author-name",V:b.author},{D:"div",H:"html5-subscribe-button-container"}]}]});g.I(this,this.o);this.o.aa(this.element);this.A=new g.uU("\uad6c\ub3c5",null,"\uad6c\ub3c5 \ucde8\uc18c",null,!0,!1,b.oe,b.subscribed,"trailer-endscreen",null,null,a);g.I(this,this.A);this.A.aa(this.o.g["html5-subscribe-button-container"]);
this.hide()},j3=function(a){var b=g.V(a),c=g.Dw||g.Ph?{style:"will-change: opacity"}:void 0,d=b.g,e=["ytp-videowall-still"];
b.l&&e.push("ytp-videowall-show-text");g.R.call(this,{D:"a",W:e,O:{href:"{{url}}",target:d?"_blank":"","aria-label":"{{aria_label}}","data-is-live":"{{is_live}}","data-is-list":"{{is_list}}","data-is-mix":"{{is_mix}}"},K:[{D:"div",H:"ytp-videowall-still-image",O:{style:"{{background}}"}},{D:"span",H:"ytp-videowall-still-info",K:[{D:"span",H:"ytp-videowall-still-info-bg",K:[{D:"span",H:"ytp-videowall-still-info-content",O:c,K:[{D:"span",H:"ytp-videowall-still-info-title",V:"{{title}}"},{D:"span",H:"ytp-videowall-still-info-author",
V:"{{author_and_views}}"},{D:"span",H:"ytp-videowall-still-info-live",V:"\uc2e4\uc2dc\uac04"},{D:"span",H:"ytp-videowall-still-info-duration",V:"{{duration}}"}]}]}]},{D:"span",W:["ytp-videowall-still-listlabel-regular","ytp-videowall-still-listlabel"],K:[{D:"span",H:"ytp-videowall-still-listlabel-icon"},"\uc7ac\uc0dd\ubaa9\ub85d",{D:"span",H:"ytp-videowall-still-listlabel-length",K:[" (",{D:"span",V:"{{playlist_length}}"},")"]}]},{D:"span",W:["ytp-videowall-still-listlabel-mix","ytp-videowall-still-listlabel"],
K:[{D:"span",H:"ytp-videowall-still-listlabel-mix-icon"},"\uad00\ub828 \uc7ac\uc0dd\ubaa9\ub85d",{D:"span",H:"ytp-videowall-still-listlabel-length",V:" (50+)"}]}]});this.B=d;this.l=a;this.o=null;this.A=new g.Dt(this);g.I(this,this.A);this.da("click",this.F);this.da("keypress",this.G);this.A.M(a,"videodatachange",this.C);g.V(a).C&&g.wL(a.app.T,this.element,this);this.C()},k3=function(a){g.xK(a.l,a.element);
var b=a.o.sb().videoId,c=a.o.getPlaylistId();g.eW(a.l.app,b,a.o.Zc,c,void 0,void 0,void 0)},l3=function(a){b3.call(this,a,"videowall-endscreen");
this.L=a;this.F=0;this.A=[];this.G=this.C=this.B=null;this.I=this.R=!1;this.ba=new g.Dt(this);g.I(this,this.ba);this.J=new g.L(g.Ma(g.J,this.element,"ytp-show-tiles"),0);g.I(this,this.J);var b=new g.R({D:"button",W:["ytp-button","ytp-endscreen-previous"],O:{"aria-label":"\uc774\uc804"},K:[g.oO()]});g.I(this,b);b.aa(this.element);b.da("click",this.NE,this);this.N=new g.lv({D:"div",H:"ytp-endscreen-content"});g.I(this,this.N);this.N.aa(this.element);b=new g.R({D:"button",W:["ytp-button","ytp-endscreen-next"],
O:{"aria-label":"\ub2e4\uc74c"},K:[g.pO()]});g.I(this,b);b.aa(this.element);b.da("click",this.ME,this);this.o=new c3(a);g.I(this,this.o);g.tK(this.l,this.o.element,4);this.hide()},m3=function(a){return g.uK(a.l)&&a.Mr()&&!a.G},n3=function(a,b){return(0,g.E)(b.suggestions,function(b){b=g.TQ(b);
g.I(a,b);return b})},o3=function(a){var b=a.yp();
b!=a.R&&(a.R=b,a.l.P("autonavvisibility"))},q3=function(a){g.HK.call(this,a);
this.l=null;this.o=new g.Dt(this);g.I(this,this.o);this.A=g.V(a);p3(a)?this.l=new l3(this.g):this.A.Ga?this.l=new i3(this.g):this.l=new b3(this.g);g.I(this,this.l);g.tK(this.g,this.l.element,4);this.Ex();this.o.M(a,"videodatachange",this.Ex,this);this.o.M(a,"crn_endscreen",this.RC,this);this.o.M(a,"crx_endscreen",this.SC,this)},p3=function(a){a=g.V(a);
return a.dc&&!a.Ga};
g.r(b3,g.rv);b3.prototype.create=function(){this.created=!0};
b3.prototype.xp=function(){this.created=!1};
b3.prototype.Mr=function(){return!1};
b3.prototype.yp=function(){return!1};g.r(c3,g.R);g.h=c3.prototype;g.h.vk=function(){this.C&&(this.G.stop(),this.La(this.F),this.F=null,this.C.close(),this.C=null)};
g.h.lw=function(){g.qv(this,g.SJ(this.l))};
g.h.KI=function(){window.focus();this.vk()};
g.h.hide=function(){g.R.prototype.hide.call(this)};
g.h.mn=function(a){a=a||g.T(g.V(this.l).experiments,"autoplay_time")||1E4;var b=Math.min(g.P()-this.I,a);a=Math.min(b/a,1);this.J.setAttribute("stroke-dashoffset",-211*(a+1));1<=a&&3!=this.l.Ea()?h3(this,!0):this.o&&this.o.start()};
g.h.UI=function(a){!g.fe(this.A.element,g.qt(a))&&g.CQ(a,this.l)&&h3(this)};
g.h.aH=function(){g.UJ(this.l,!0)};
g.h.hI=function(a){this.l.Ea();this.show();e3(this,a)};
g.h.Oy=function(a){this.l.Ea();this.B&&this.B.sb().videoId==a.sb().videoId||d3(this,a)};
g.h.iI=function(){this.l.Ea();f3(this);this.hide()};
g.h.U=function(){f3(this);this.vk();g.R.prototype.U.call(this)};g.r(i3,b3);g.r(j3,g.R);j3.prototype.F=function(a){g.CQ(a,this.l,this.B,this.o.Zc||void 0)&&k3(this)};
j3.prototype.G=function(a){switch(a.keyCode){case 13:case 32:g.wt(a)||(k3(this),g.vt(a))}};
j3.prototype.C=function(){var a=this.l.getVideoData(),b=g.V(this.l);this.B=a.isDni?!1:b.g};g.r(l3,b3);g.h=l3.prototype;g.h.create=function(){b3.prototype.create.call(this);var a=this.l.getVideoData();a&&(this.B=n3(this,a),this.C=a);this.nf();this.ba.M(this.l,"appresize",this.nf);this.ba.M(this.l,"onVideoAreaChange",this.nf);this.ba.M(this.l,"videodatachange",this.OE);this.ba.M(this.l,"autonavchange",this.hv);this.ba.M(this.l,"autonavcancel",this.LE);this.ba.M(this.element,"transitionend",this.eK)};
g.h.xp=function(){g.Ft(this.ba);g.bf(this.A);this.A=[];this.B=null;b3.prototype.xp.call(this);g.gq(this.element,"ytp-show-tiles");this.J.stop()};
g.h.Mr=function(){return 1!=this.C.autonavState};
g.h.show=function(){b3.prototype.show.call(this);g.gq(this.element,"ytp-show-tiles");g.V(this.l).l?g.uq(this.J):this.J.start();(this.I||this.G&&this.G!=this.C.clientPlaybackNonce)&&g.UJ(this.l,!1);m3(this)?(o3(this),2==this.C.autonavState?g.S(g.V(this.l).experiments,"fast_autonav_in_background")&&3==this.l.lf()?h3(this.o,!0):e3(this.o):3==this.C.autonavState&&g3(this.o)):(g.UJ(this.l,!0),o3(this))};
g.h.hide=function(){b3.prototype.hide.call(this);g3(this.o);o3(this)};
g.h.eK=function(a){g.qt(a)==this.element&&this.nf()};
g.h.nf=function(){if(this.B&&this.B.length){g.J(this.element,"ytp-endscreen-paginate");var a=g.jK(this.L,!0),b=g.Gv(this.L);b&&(b=b.Hc()?48:32,a.width-=2*b);var c=a.width/a.height,d=96/54,e=b=2,f=Math.max(a.width/96,2),k=Math.max(a.height/54,2),l=this.B.length,m=Math.pow(2,2);var n=l*m+(Math.pow(2,2)-m);n+=Math.pow(2,2)-m;for(n-=m;0<n&&(b<f||e<k);){var q=b/2,u=e/2,w=b<=f-2&&n>=u*m,H=e<=k-2&&n>=q*m;if((q+1)/u*d/c>c/(q/(u+1)*d)&&H)n-=q*m,e+=2;else if(w)n-=u*m,b+=2;else if(H)n-=q*m,e+=2;else break}d=
!1;n>=3*m&&6>=l*m-n&&(4<=e||4<=b)&&(d=!0);m=96*b;n=54*e;c=m/n<c?a.height/n:a.width/m;c=Math.min(c,2);m*=c;n*=c;m*=g.pd(a.width/m||1,1,1.21);n*=g.pd(a.height/n||1,1,1.21);m=Math.floor(Math.min(a.width,m));n=Math.floor(Math.min(a.height,n));a=this.N.element;g.ei(a,m,n);g.Jh(a,{marginLeft:m/-2+"px",marginTop:n/-2+"px"});d3(this.o,this.B[0]);g.K(this.element,"ytp-endscreen-takeover",m3(this));o3(this);m+=4;n+=4;for(f=c=0;f<b;f++)for(k=0;k<e;k++)if(q=c,u=0,d&&f>=b-2&&k>=e-2?u=1:0==k%2&&0==f%2&&(2>k&&2>
f?0==k&&0==f&&(u=2):u=2),q=g.qd(q+this.F,l),0!=u){w=this.A[c];w||(w=new j3(this.l),this.A[c]=w,a.appendChild(w.element));H=Math.floor(n*k/e);var F=Math.floor(m*f/b),M=Math.floor(n*(k+u)/e)-H-4,aa=Math.floor(m*(f+u)/b)-F-4;g.Uh(w.element,F,H);g.ei(w.element,aa,M);g.Jh(w.element,"transitionDelay",(k+f)/20+"s");g.K(w.element,"ytp-videowall-still-mini",1==u);g.K(w.element,"ytp-videowall-still-large",2<u);u=w;q=this.B[q];u.o!=q&&(u.o=q,a3(u,q,g.V(u.l),g.eq(u.element,"ytp-videowall-still-large")?"hqdefault.jpg":
"mqdefault.jpg"),q=(q=q.Zc)&&q.itct)&&(w=u.l,g.V(w).C&&g.xL(w.app.T,u.element,q));c++}g.K(this.element,"ytp-endscreen-paginate",c<l);for(b=this.A.length-1;b>=c;b--)e=this.A[b],g.Zd(e.element),g.af(e);this.A.length=c}};
g.h.OE=function(){var a=this.l.getVideoData();this.C!=a&&(this.F=0,this.B=n3(this,a),this.C=a,this.nf())};
g.h.ME=function(){this.F+=this.A.length;this.nf()};
g.h.NE=function(){this.F-=this.A.length;this.nf()};
g.h.YB=function(){return!!this.o.o};
g.h.hv=function(a){1==a?(this.I=!1,this.G=this.C.clientPlaybackNonce,f3(this.o),this.Ha()&&this.nf()):(this.I=!0,this.Ha()&&m3(this)&&(2==a?e3(this.o):3==a&&g3(this.o)))};
g.h.LE=function(a){if(a){for(a=0;a<this.A.length;a++)g.yK(this.L,this.A[a].element,!0);this.hv(1)}else this.G=null,this.I=!1;this.nf()};
g.h.yp=function(){return this.Ha()&&m3(this)};g.r(q3,g.HK);g.h=q3.prototype;g.h.Hu=function(){var a=this.g.getVideoData(),b=!!(a&&a.suggestions&&a.suggestions.length);b=!p3(this.g)||b;a=g.KC(a,"ypc_module");var c=g.fW(this.g.app);return b&&!a&&!c};
g.h.Gu=function(){return this.l.yp()};
g.h.VB=function(){return this.Gu()?this.l.YB():!1};
g.h.U=function(){g.pK(this.g,"endscreen");g.HK.prototype.U.call(this)};
g.h.load=function(){g.HK.prototype.load.call(this);this.l.show()};
g.h.unload=function(){g.HK.prototype.unload.call(this);this.l.hide();this.l.xp()};
g.h.RC=function(a){this.Hu()&&(this.l.created||this.l.create(),"load"==a.getId()&&this.load())};
g.h.SC=function(a){"load"==a.getId()&&this.loaded&&this.unload()};
g.h.Ex=function(){g.pK(this.g,"endscreen");var a=Math.max(1E3*(this.g.getVideoData().lengthSeconds-10),0);a=new g.hE(a,0x8000000000000,{id:"preload",namespace:"endscreen"});g.I(this,a);var b=new g.hE(0x8000000000000,0x8000000000000,{id:"load",priority:6,namespace:"endscreen"});g.I(this,b);g.mK(this.g,[a,b])};g.LQ.endscreen=q3;})(_yt_player);
